name: flutter_app_template
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: 9.0.0
  flutter_bloc: 9.1.1
  bloc_concurrency: ^0.3.0
  stream_transform: 2.1.1
  cupertino_icons: 1.0.8
  provider: 6.1.5
  intl: 0.20.2
  flutter_svg: 2.2.0
  flutter_localizations:
    sdk: flutter
  lottie: 3.3.1
  talker_flutter: 4.9.3
  talker_dio_logger: ^4.9.3
  talker_bloc_logger: ^4.9.3
  equatable: 2.0.7
  dio: 5.8.0+1
  uuid: 4.5.1
  go_router: ^16.0.0
  shared_preferences: 2.3.5
  flutter_secure_storage: ^9.2.4
  flutter_dotenv: 5.2.1 
  ### основной сервис с интерфейсами
  
  i_app_services:
    path: ./app_services/i_app_services

  ### реализация сервисов ###
  ### В зависимости от платформы ###
  app_services:
    path: app_services/base/app_services ### Базовая реализация ###
    # path: app_services/aurora/app_services ### Аврора реализация ###
    # path: app_services/hms/app_services ### HarmonyOS реализация ###

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.6.0
  flutter_lints: 6.0.0
  intl_utils: 2.8.11
  flutter_gen_runner: 5.11.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - env/
    - assets/icons/
    - assets/fonts/
    - assets/lottie/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400

flutter_gen:
  output: lib/gen/
  
  integrations:
    flutter_svg: true
    lottie: true

flutter_intl:
  enabled: true
  arb_dir: lib/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/l10n/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
  main_locale: ru